"use client";
import { useMemo, useState } from "react";
import { AgeRange, calculatePrice, Course, courses, locations, money, Package, packages } from "@/lib/pricing";

const ages: AgeRange[] = ["18-24", "25-34", "35-45", "46+"];
const defaultSlots = ["Weekdays · 9:00 AM WAT", "Weekdays · 11:00 AM WAT", "Weekdays · 5:00 PM WAT", "Saturdays · 10:00 AM WAT"];

export function EnrollmentFlow() {
  const [step, setStep] = useState(1); const [course, setCourse] = useState<Course>(); const [pack, setPack] = useState<Package>();
  const [age, setAge] = useState<AgeRange>("18-24"); const [location, setLocation] = useState("lagos island"); const [slots, setSlots] = useState<string[]>([]);
  const [status, setStatus] = useState<"idle"|"sending"|"done"|"error">("idle"); const [reference, setReference] = useState("");
  const price = useMemo(() => course && pack ? calculatePrice(course, pack, age, location) : null, [course, pack, age, location]);
  const needsSchedule = pack === "group" || pack === "personal" || pack === "physical";
  function toggleSlot(slot:string){setSlots(v=>v.includes(slot)?v.filter(x=>x!==slot):[...v,slot].slice(-(pack==="personal"||pack==="physical"?3:1)));}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("sending");const form=new FormData(e.currentTarget);const payload={course,packageType:pack,ageRange:age,location,name:form.get("name"),whatsapp:form.get("whatsapp"),preferredSlots:slots,quotedAmount:price?.kind==="price"?price.amount:null,consent:form.get("consent")==="on"};const res=await fetch("/api/enrollments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(res.ok){setReference(data.reference);setStatus("done");}else setStatus("error");}
  if(status==="done") return <section className="flow-shell success-card"><span className="flow-kicker">APPLICATION RECEIVED</span><h1>We’ll contact you on WhatsApp.</h1><p>Your reference is <strong>{reference}</strong>. An Arcane Academy enrollment specialist will call you, confirm your schedule and provide the official payment account.</p><a className="flow-primary" href={`https://wa.me/2349029840305?text=${encodeURIComponent(`Hello Arcane Academy, I just applied. My reference is ${reference}.`)}`}>Message Arcane on WhatsApp</a></section>;
  return <section className="flow-shell"><div className="flow-heading"><span className="flow-kicker">ENROLLMENT · STEP {step} OF 4</span><h1>Build your learning plan.</h1><p>Choose what you want to build, how you want to learn, and a time that works for you.</p></div><div className="progress"><i style={{width:`${step*25}%`}} /></div>
    {step===1&&<div className="choice-grid">{(Object.keys(courses) as Course[]).map(k=><button className={`choice ${course===k?"selected":""}`} key={k} onClick={()=>setCourse(k)}><small>COURSE</small><h2>{courses[k].name}</h2><p>{courses[k].description}</p></button>)}</div>}
    {step===2&&<div className="choice-grid package-grid">{(Object.keys(packages) as Package[]).map(k=>{const unavailable=course==="android"&&k==="self_paced";return <button disabled={unavailable} className={`choice ${pack===k?"selected":""}`} key={k} onClick={()=>setPack(k)}><small>{unavailable?"COMING SOON":"LEARNING PACKAGE"}</small><h2>{packages[k].name}</h2><p>{packages[k].detail}</p></button>})}</div>}
    {step===3&&<div className="details-panel"><div className="form-grid"><label>Age range<select value={age} onChange={e=>setAge(e.target.value as AgeRange)}>{ages.map(x=><option key={x}>{x}</option>)}</select></label><label>Location<select value={location} onChange={e=>setLocation(e.target.value)}>{locations.map(x=><option value={x} key={x}>{x.replace(/\b\w/g,c=>c.toUpperCase())}</option>)}</select></label></div>{needsSchedule&&<><h3>Preferred {pack==="physical"?"dates":"class time"}</h3><p className="muted">This is a request. We’ll confirm availability before payment. You may choose up to {pack==="group"?1:3}.</p><div className="slots">{defaultSlots.map((s,i)=><button key={s} disabled={i===3&&pack==="group"} className={slots.includes(s)?"selected":""} onClick={()=>toggleSlot(s)}>{s}<small>{i===3&&pack==="group"?"Unavailable":"Available"}</small></button>)}</div></>}</div>}
    {step===4&&<form className="details-panel" onSubmit={submit}><div className="price-summary"><small>YOUR {price?.kind==="quote"?"QUOTE":"PRICE"}</small><strong>{price?.kind==="price"?money.format(price.amount):"We’ll prepare a bespoke quote"}</strong>{price?.kind==="price"&&price.discount>0&&<span>Arcane Access Discount applied</span>}<p>Payment details are provided only after an Arcane Academy representative calls you.</p></div><div className="form-grid"><label>Full name<input name="name" required minLength={2}/></label><label>WhatsApp phone number<input name="whatsapp" type="tel" required placeholder="+234…"/></label></div><label className="consent"><input name="consent" type="checkbox" required/> I agree that Arcane Academy may contact me about this application and process my information according to its privacy notice.</label>{status==="error"&&<p className="form-error">We couldn’t save your application. Please try again or contact us on WhatsApp.</p>}<button className="flow-primary" disabled={status==="sending"}>{status==="sending"?"Submitting…":"Submit application"}</button></form>}
    <div className="flow-actions">{step>1&&<button onClick={()=>setStep(s=>s-1)}>Back</button>}{step<4&&<button className="flow-primary" disabled={(step===1&&!course)||(step===2&&!pack)||(step===3&&needsSchedule&&slots.length===0)} onClick={()=>setStep(s=>s+1)}>Continue</button>}</div>
  </section>;
}
