drop function public.submit_enrollment(text,text,text,text,text,text,text,jsonb,integer,text);
create function public.submit_enrollment(p_reference text,p_name text,p_whatsapp text,p_location text,p_age_range text,p_course text,p_package_type text,p_preferred_slots jsonb,p_quoted_amount integer,p_price_status text,p_slot_id uuid default null) returns text language plpgsql security definer set search_path='' as $$ begin
 if length(trim(p_name))<2 or length(trim(p_whatsapp))<7 or p_age_range not in ('18-24','25-34','35-45','46+') or p_course not in ('web','android') or p_package_type not in ('group','personal','self_paced','physical') or p_price_status not in ('price','quote') then raise exception 'Invalid enrollment';end if;
 if p_slot_id is not null and not exists(select 1 from public.availability_slots where id=p_slot_id and course=p_course and package_type=p_package_type and is_active and status='available') then raise exception 'Schedule unavailable';end if;
 insert into public.enrollments(reference,name,whatsapp,location,age_range,course,package_type,preferred_slots,quoted_amount,price_status,consent_at,slot_id) values(p_reference,left(trim(p_name),120),left(trim(p_whatsapp),30),left(trim(p_location),80),p_age_range,p_course,p_package_type,coalesce(p_preferred_slots,'[]'::jsonb),p_quoted_amount,p_price_status,now(),p_slot_id);
 return p_reference;end $$;
revoke all on function public.submit_enrollment(text,text,text,text,text,text,text,jsonb,integer,text,uuid) from public;grant execute on function public.submit_enrollment(text,text,text,text,text,text,text,jsonb,integer,text,uuid) to anon;

create function public.public_enrollment_status(p_reference text) returns table(reference text,course text,package_type text,status text,price_status text,quoted_amount integer,created_at timestamptz) language sql stable security definer set search_path='' as $$ select e.reference,e.course,e.package_type,e.status,e.price_status,e.quoted_amount,e.created_at from public.enrollments e where upper(e.reference)=upper(p_reference) limit 1 $$;
revoke all on function public.public_enrollment_status(text) from public;grant execute on function public.public_enrollment_status(text) to anon,authenticated;
