create extension if not exists pgcrypto;
create type public.staff_role as enum ('owner','admin','enrollment','tutor');
create type public.staff_status as enum ('pending','approved','rejected','expired');

create table public.staff_profiles (user_id uuid primary key references auth.users(id) on delete cascade,email text not null unique,name text,role public.staff_role not null default 'enrollment',status public.staff_status not null default 'pending',request_expires_at timestamptz,approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now());
create table public.enrollments (id uuid primary key default gen_random_uuid(),reference text not null unique,name text not null,whatsapp text not null,location text not null,age_range text not null check(age_range in ('18-24','25-34','35-45','46+')),course text not null check(course in ('web','android')),package_type text not null check(package_type in ('group','personal','self_paced','physical')),preferred_slots jsonb not null default '[]',quoted_amount integer check(quoted_amount is null or quoted_amount>=5000),price_status text not null check(price_status in ('price','quote')),status text not null default 'new',assigned_to uuid references auth.users(id),schedule_priority_expires_at timestamptz,consent_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.availability_slots (id uuid primary key default gen_random_uuid(),course text not null,package_type text not null check(package_type in ('group','personal','physical')),starts_at timestamptz not null,duration_minutes integer not null default 60,status text not null default 'available',capacity integer not null default 1,cohort_name text,created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(),enrollment_id uuid not null references public.enrollments(id),expected_amount integer not null,received_amount integer,transfer_reference text,status text not null default 'unpaid' check(status in ('unpaid','processing','fully_paid','failed','waived','refunded','deposit_paid')),verified_by uuid references auth.users(id),verified_at timestamptz,created_at timestamptz not null default now());
create table public.receipts (id uuid primary key default gen_random_uuid(),payment_id uuid not null references public.payments(id),receipt_number text not null unique,issued_at timestamptz not null default now());
create table public.certificates (id uuid primary key default gen_random_uuid(),enrollment_id uuid not null unique references public.enrollments(id),verification_number text not null unique,learner_name text not null,course text not null,project_approved_by uuid references auth.users(id),status text not null default 'draft',issued_at timestamptz,created_at timestamptz not null default now());
create table public.visitor_events (id bigint generated always as identity primary key,visited_at timestamptz not null default now(),path text not null,device_type text not null,browser text not null,os text not null,referrer_domain text);
create index enrollments_assigned_status_idx on public.enrollments(assigned_to,status);
create index visitor_events_visited_at_idx on public.visitor_events(visited_at desc);
create index availability_starts_at_idx on public.availability_slots(starts_at,status);

alter table public.staff_profiles enable row level security;alter table public.enrollments enable row level security;alter table public.availability_slots enable row level security;alter table public.payments enable row level security;alter table public.receipts enable row level security;alter table public.certificates enable row level security;alter table public.visitor_events enable row level security;
revoke all on all tables in schema public from anon, authenticated;
grant select,insert,update on public.staff_profiles,public.enrollments,public.availability_slots,public.payments,public.receipts,public.certificates to authenticated;

create policy "staff read own profile" on public.staff_profiles for select to authenticated using ((select auth.uid())=user_id);
create policy "approved admins read staff" on public.staff_profiles for select to authenticated using (exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved' and p.role in ('owner','admin')));
create policy "approved staff read assigned enrollments" on public.enrollments for select to authenticated using (assigned_to=(select auth.uid()) or exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved' and p.role in ('owner','admin')));
create policy "approved staff read availability" on public.availability_slots for select to authenticated using (exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved'));
create policy "admins manage availability" on public.availability_slots for all to authenticated using (exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved' and p.role in ('owner','admin'))) with check (exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved' and p.role in ('owner','admin')));
create policy "staff read assigned payments" on public.payments for select to authenticated using (exists(select 1 from public.enrollments e where e.id=enrollment_id and (e.assigned_to=(select auth.uid()) or exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved' and p.role in ('owner','admin')))));
create policy "staff read receipts" on public.receipts for select to authenticated using (exists(select 1 from public.payments pay join public.enrollments e on e.id=pay.enrollment_id where pay.id=payment_id and (e.assigned_to=(select auth.uid()) or exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved' and p.role in ('owner','admin')))));
create policy "staff read certificates" on public.certificates for select to authenticated using (exists(select 1 from public.enrollments e where e.id=enrollment_id and (e.assigned_to=(select auth.uid()) or exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved' and p.role in ('owner','admin')))));
create policy "admins read analytics" on public.visitor_events for select to authenticated using (exists(select 1 from public.staff_profiles p where p.user_id=(select auth.uid()) and p.status='approved' and p.role in ('owner','admin')));

comment on table public.visitor_events is 'Privacy-conscious aggregate visit events. Never store raw IP addresses or persistent fingerprints.';
