create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create type public.staff_role as enum ('owner','admin','enrollment','tutor');
create type public.staff_status as enum ('pending','approved','rejected','expired');

create table public.staff_profiles (user_id uuid primary key references auth.users(id) on delete cascade,email text not null unique,name text,role public.staff_role not null default 'enrollment',status public.staff_status not null default 'pending',request_expires_at timestamptz,approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now());
create table public.enrollments (id uuid primary key default gen_random_uuid(),reference text not null unique,name text not null,whatsapp text not null,location text not null,age_range text not null check(age_range in ('18-24','25-34','35-45','46+')),course text not null check(course in ('web','android')),package_type text not null check(package_type in ('group','personal','self_paced','physical')),preferred_slots jsonb not null default '[]',quoted_amount integer check(quoted_amount is null or quoted_amount>=5000),price_status text not null check(price_status in ('price','quote')),status text not null default 'new',assigned_to uuid references auth.users(id),schedule_priority_expires_at timestamptz,consent_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.availability_slots (id uuid primary key default gen_random_uuid(),course text not null,package_type text not null check(package_type in ('group','personal','physical')),starts_at timestamptz not null,duration_minutes integer not null default 60,status text not null default 'available',capacity integer not null default 1,cohort_name text,created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(),enrollment_id uuid not null references public.enrollments(id),expected_amount integer not null,received_amount integer,transfer_reference text,status text not null default 'unpaid' check(status in ('unpaid','processing','fully_paid','failed','waived','refunded','deposit_paid')),verified_by uuid references auth.users(id),verified_at timestamptz,created_at timestamptz not null default now());
create table public.receipts (id uuid primary key default gen_random_uuid(),payment_id uuid not null references public.payments(id),receipt_number text not null unique,issued_at timestamptz not null default now());
create table public.certificates (id uuid primary key default gen_random_uuid(),enrollment_id uuid not null unique references public.enrollments(id),verification_number text not null unique,learner_name text not null,course text not null,project_approved_by uuid references auth.users(id),status text not null default 'draft',issued_at timestamptz,created_at timestamptz not null default now());
create table public.visitor_events (id bigint generated always as identity primary key,visited_at timestamptz not null default now(),path text not null,device_type text not null,browser text not null,os text not null,referrer_domain text);
create index enrollments_assigned_status_idx on public.enrollments(assigned_to,status);
create index visitor_events_visited_at_idx on public.visitor_events(visited_at desc);
create index availability_starts_at_idx on public.availability_slots(starts_at,status);

create function private.is_approved_staff(check_user uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.staff_profiles where user_id=check_user and status='approved') $$;
create function private.is_admin(check_user uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.staff_profiles where user_id=check_user and status='approved' and role in ('owner','admin')) $$;
create function private.handle_new_staff() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.staff_profiles(user_id,email,name,role,status,request_expires_at,approved_at) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',new.email),case when lower(new.email)='ngbridz@gmail.com' then 'owner'::public.staff_role else 'enrollment'::public.staff_role end,case when lower(new.email)='ngbridz@gmail.com' then 'approved'::public.staff_status else 'pending'::public.staff_status end,now()+interval '1 month',case when lower(new.email)='ngbridz@gmail.com' then now() else null end) on conflict(user_id) do nothing; return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_staff();

create function public.submit_enrollment(p_reference text,p_name text,p_whatsapp text,p_location text,p_age_range text,p_course text,p_package_type text,p_preferred_slots jsonb,p_quoted_amount integer,p_price_status text) returns text language plpgsql security definer set search_path='' as $$ begin if length(trim(p_name))<2 or length(trim(p_whatsapp))<7 or p_age_range not in ('18-24','25-34','35-45','46+') or p_course not in ('web','android') or p_package_type not in ('group','personal','self_paced','physical') or p_price_status not in ('price','quote') then raise exception 'Invalid enrollment'; end if; insert into public.enrollments(reference,name,whatsapp,location,age_range,course,package_type,preferred_slots,quoted_amount,price_status,consent_at) values(p_reference,left(trim(p_name),120),left(trim(p_whatsapp),30),left(trim(p_location),80),p_age_range,p_course,p_package_type,coalesce(p_preferred_slots,'[]'::jsonb),p_quoted_amount,p_price_status,now()); return p_reference; end $$;
create function public.record_visit(p_path text,p_device_type text,p_browser text,p_os text,p_referrer_domain text) returns void language plpgsql security definer set search_path='' as $$ begin insert into public.visitor_events(path,device_type,browser,os,referrer_domain) values(left(coalesce(p_path,'/'),250),left(coalesce(p_device_type,'unknown'),30),left(coalesce(p_browser,'Other'),40),left(coalesce(p_os,'Other'),40),left(p_referrer_domain,120)); end $$;
create function public.verify_certificate(p_verification text) returns table(verification_number text,learner_name text,course text,issued_at timestamptz,status text) language sql stable security definer set search_path='' as $$ select c.verification_number,c.learner_name,c.course,c.issued_at,c.status from public.certificates c where c.verification_number=p_verification and c.status='issued' limit 1 $$;
revoke all on function public.submit_enrollment(text,text,text,text,text,text,text,jsonb,integer,text) from public;
revoke all on function public.record_visit(text,text,text,text,text) from public;
revoke all on function public.verify_certificate(text) from public;
grant execute on function public.submit_enrollment(text,text,text,text,text,text,text,jsonb,integer,text) to anon;
grant execute on function public.record_visit(text,text,text,text,text) to anon;
grant execute on function public.verify_certificate(text) to anon,authenticated;

alter table public.staff_profiles enable row level security; alter table public.enrollments enable row level security; alter table public.availability_slots enable row level security; alter table public.payments enable row level security; alter table public.receipts enable row level security; alter table public.certificates enable row level security; alter table public.visitor_events enable row level security;
revoke all on all tables in schema public from anon,authenticated;
grant select,insert,update on public.staff_profiles,public.enrollments,public.availability_slots,public.payments,public.receipts,public.certificates,public.visitor_events to authenticated;
create policy "staff read profiles" on public.staff_profiles for select to authenticated using(user_id=(select auth.uid()) or private.is_admin((select auth.uid())));
create policy "admins update staff" on public.staff_profiles for update to authenticated using(private.is_admin((select auth.uid()))) with check(private.is_admin((select auth.uid())));
create policy "staff read assigned enrollments" on public.enrollments for select to authenticated using((assigned_to=(select auth.uid()) and private.is_approved_staff((select auth.uid()))) or private.is_admin((select auth.uid())));
create policy "staff update assigned enrollments" on public.enrollments for update to authenticated using((assigned_to=(select auth.uid()) and private.is_approved_staff((select auth.uid()))) or private.is_admin((select auth.uid()))) with check((assigned_to=(select auth.uid()) and private.is_approved_staff((select auth.uid()))) or private.is_admin((select auth.uid())));
create policy "approved staff read availability" on public.availability_slots for select to authenticated using(private.is_approved_staff((select auth.uid())));
create policy "admins manage availability" on public.availability_slots for all to authenticated using(private.is_admin((select auth.uid()))) with check(private.is_admin((select auth.uid())));
create policy "staff read assigned payments" on public.payments for select to authenticated using(exists(select 1 from public.enrollments e where e.id=enrollment_id and ((e.assigned_to=(select auth.uid()) and private.is_approved_staff((select auth.uid()))) or private.is_admin((select auth.uid())))));
create policy "staff read receipts" on public.receipts for select to authenticated using(exists(select 1 from public.payments pay join public.enrollments e on e.id=pay.enrollment_id where pay.id=payment_id and ((e.assigned_to=(select auth.uid()) and private.is_approved_staff((select auth.uid()))) or private.is_admin((select auth.uid())))));
create policy "staff read certificates" on public.certificates for select to authenticated using(exists(select 1 from public.enrollments e where e.id=enrollment_id and ((e.assigned_to=(select auth.uid()) and private.is_approved_staff((select auth.uid()))) or private.is_admin((select auth.uid())))));
create policy "admins read analytics" on public.visitor_events for select to authenticated using(private.is_admin((select auth.uid())));
comment on table public.visitor_events is 'Privacy-conscious aggregate visit events. Never store raw IP addresses or persistent fingerprints.';
