alter table public.enrollments add column if not exists slot_id uuid references public.availability_slots(id), add column if not exists follow_up_at timestamptz, add column if not exists project_status text not null default 'not_started', add column if not exists project_url text;
alter table public.availability_slots add column if not exists enrolled_count integer not null default 0, add column if not exists is_active boolean not null default true;
alter table public.payments add column if not exists notes text;

create table public.lead_notes(id uuid primary key default gen_random_uuid(),enrollment_id uuid not null references public.enrollments(id) on delete cascade,body text not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,title text not null,body text not null,kind text not null default 'info',href text,read_at timestamptz,created_at timestamptz not null default now());
create table public.push_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,endpoint text not null unique,p256dh text not null,auth text not null,created_at timestamptz not null default now());
create table public.audit_log(id bigint generated always as identity primary key,actor_id uuid references auth.users(id),action text not null,entity_type text not null,entity_id text,details jsonb not null default '{}',created_at timestamptz not null default now());
create table public.tutor_payments(id uuid primary key default gen_random_uuid(),tutor_id uuid not null references auth.users(id),enrollment_id uuid references public.enrollments(id),amount integer not null,status text not null default 'unpaid',reference text,paid_at timestamptz,created_at timestamptz not null default now());

create index lead_notes_enrollment_idx on public.lead_notes(enrollment_id,created_at desc);create index notifications_user_idx on public.notifications(user_id,created_at desc);create index push_subscriptions_user_idx on public.push_subscriptions(user_id);create index audit_log_created_idx on public.audit_log(created_at desc);create index enrollments_slot_idx on public.enrollments(slot_id);create index tutor_payments_tutor_idx on public.tutor_payments(tutor_id);
alter table public.lead_notes enable row level security;alter table public.notifications enable row level security;alter table public.push_subscriptions enable row level security;alter table public.audit_log enable row level security;alter table public.tutor_payments enable row level security;
revoke all on public.lead_notes,public.notifications,public.push_subscriptions,public.audit_log,public.tutor_payments from anon,authenticated;
grant select,insert,update,delete on public.lead_notes,public.notifications,public.push_subscriptions,public.audit_log,public.tutor_payments to authenticated;

create policy "staff notes" on public.lead_notes for all to authenticated using(private.is_approved_staff((select auth.uid())) and exists(select 1 from public.enrollments e where e.id=enrollment_id and (e.assigned_to=(select auth.uid()) or private.is_admin((select auth.uid()))))) with check(private.is_approved_staff((select auth.uid())) and created_by=(select auth.uid()));
create policy "own notifications" on public.notifications for select to authenticated using(user_id=(select auth.uid()));create policy "update own notifications" on public.notifications for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "own push subscriptions" on public.push_subscriptions for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "admins read audit" on public.audit_log for select to authenticated using(private.is_admin((select auth.uid())));
create policy "tutor payment access" on public.tutor_payments for select to authenticated using(tutor_id=(select auth.uid()) or private.is_admin((select auth.uid())));

create policy "admins insert slots" on public.availability_slots for insert to authenticated with check(private.is_admin((select auth.uid())));
create policy "admins delete slots" on public.availability_slots for delete to authenticated using(private.is_admin((select auth.uid())));
create policy "admins insert payments" on public.payments for insert to authenticated with check(private.is_admin((select auth.uid())) or private.is_approved_staff((select auth.uid())));
create policy "admins update payments" on public.payments for update to authenticated using(private.is_admin((select auth.uid())) or private.is_approved_staff((select auth.uid()))) with check(private.is_admin((select auth.uid())) or private.is_approved_staff((select auth.uid())));
create policy "tutors insert certificates" on public.certificates for insert to authenticated with check(private.is_approved_staff((select auth.uid())));
create policy "tutors update certificates" on public.certificates for update to authenticated using(private.is_approved_staff((select auth.uid()))) with check(private.is_approved_staff((select auth.uid())));

create function private.notify_admins(p_title text,p_body text,p_kind text,p_href text) returns void language sql security definer set search_path='' as $$ insert into public.notifications(user_id,title,body,kind,href) select user_id,p_title,p_body,p_kind,p_href from public.staff_profiles where status='approved' and role in ('owner','admin') $$;
create function private.after_enrollment() returns trigger language plpgsql security definer set search_path='' as $$ begin perform private.notify_admins('New enrollment',new.name||' applied for '||new.course||' '||new.package_type,'lead','/admin?tab=Leads');return new;end $$;
create trigger enrollment_notification after insert on public.enrollments for each row execute function private.after_enrollment();

create function public.admin_dashboard_action(p_action text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); eid uuid; sid uuid; pid uuid; certno text;
begin
 if uid is null or not private.is_approved_staff(uid) then raise exception 'Unauthorized'; end if;
 if p_action='update_lead' then eid:=(p_payload->>'id')::uuid; update public.enrollments set status=coalesce(p_payload->>'status',status),assigned_to=case when p_payload?'assigned_to' then nullif(p_payload->>'assigned_to','')::uuid else assigned_to end,follow_up_at=case when p_payload?'follow_up_at' then nullif(p_payload->>'follow_up_at','')::timestamptz else follow_up_at end,slot_id=case when p_payload?'slot_id' then nullif(p_payload->>'slot_id','')::uuid else slot_id end,schedule_priority_expires_at=case when p_payload->>'status'='awaiting_payment' then now()+interval '48 hours' else schedule_priority_expires_at end,updated_at=now() where id=eid and (private.is_admin(uid) or assigned_to=uid);insert into public.audit_log(actor_id,action,entity_type,entity_id,details) values(uid,p_action,'enrollment',eid::text,p_payload);return jsonb_build_object('ok',true);
 elsif p_action='add_slot' and private.is_admin(uid) then insert into public.availability_slots(course,package_type,starts_at,capacity,cohort_name,created_by,status) values(p_payload->>'course',p_payload->>'package_type',(p_payload->>'starts_at')::timestamptz,coalesce((p_payload->>'capacity')::int,case when p_payload->>'package_type'='group' then 20 else 1 end),p_payload->>'cohort_name',uid,'available') returning id into sid;return jsonb_build_object('ok',true,'id',sid);
 elsif p_action='toggle_slot' and private.is_admin(uid) then update public.availability_slots set is_active=not is_active,status=case when is_active then 'unavailable' else 'available' end where id=(p_payload->>'id')::uuid;return jsonb_build_object('ok',true);
 elsif p_action='update_price' and private.is_admin(uid) then update public.course_prices set amount=(p_payload->>'amount')::int,available=(p_payload->>'available')::boolean,updated_by=uid,updated_at=now() where course=p_payload->>'course' and package_type=p_payload->>'package_type';return jsonb_build_object('ok',true);
 elsif p_action='staff' and private.is_admin(uid) then update public.staff_profiles set status=(p_payload->>'status')::public.staff_status,role=(p_payload->>'role')::public.staff_role,approved_by=uid,approved_at=case when p_payload->>'status'='approved' then now() else approved_at end where user_id=(p_payload->>'user_id')::uuid and (role<>'owner' or exists(select 1 from public.staff_profiles where user_id=uid and role='owner'));return jsonb_build_object('ok',true);
 elsif p_action='payment' then eid:=(p_payload->>'enrollment_id')::uuid;insert into public.payments(enrollment_id,expected_amount,received_amount,transfer_reference,status,verified_by,verified_at,notes) values(eid,(p_payload->>'expected_amount')::int,(p_payload->>'received_amount')::int,p_payload->>'reference',p_payload->>'status',uid,case when p_payload->>'status'='fully_paid' then now() end,p_payload->>'notes') returning id into pid;if p_payload->>'status'='fully_paid' then update public.enrollments set status='paid',updated_at=now() where id=eid;insert into public.receipts(payment_id,receipt_number) values(pid,'RCT-'||to_char(now(),'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)));end if;return jsonb_build_object('ok',true,'id',pid);
 elsif p_action='certificate' then eid:=(p_payload->>'enrollment_id')::uuid;certno:='ARC-CERT-'||to_char(now(),'YYYY')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));insert into public.certificates(enrollment_id,verification_number,learner_name,course,project_approved_by,status,issued_at) select id,certno,name,case course when 'web' then 'AI Web Development' else 'AI Android App Development' end,uid,'issued',now() from public.enrollments where id=eid and (assigned_to=uid or private.is_admin(uid)) on conflict(enrollment_id) do update set status='issued',issued_at=now(),project_approved_by=uid;update public.enrollments set project_status='approved',status='completed' where id=eid;return jsonb_build_object('ok',true,'verification',certno);
 elsif p_action='note' then eid:=(p_payload->>'enrollment_id')::uuid;insert into public.lead_notes(enrollment_id,body,created_by) values(eid,left(p_payload->>'body',2000),uid);return jsonb_build_object('ok',true);
 else raise exception 'Unsupported action';end if;
end $$;
revoke all on function public.admin_dashboard_action(text,jsonb) from public,anon;grant execute on function public.admin_dashboard_action(text,jsonb) to authenticated;

insert into public.availability_slots(course,package_type,starts_at,capacity,cohort_name,status) values
('web','group','2026-08-15 09:00:00+01',20,'August Web Cohort','available'),('android','group','2026-08-15 11:00:00+01',20,'August Android Cohort','available'),('web','personal','2026-08-17 15:00:00+01',1,'Personal Web','available'),('android','personal','2026-08-17 17:00:00+01',1,'Personal Android','available') on conflict do nothing;
